#!/bin/sh
#gunicorn  --access-logfile - --error-log - -w 2 -b 127.0.0.1:5000 clusterapp:app

export PYTHONPATH=/usr/local/bin

start() { 
    echo "Upgrading Database"
    /usr/local/bin/clusterapp.py db upgrade
    
    echo "Starting Celery Worker"
    celery multi start worker -A clusterapp.celery  --pidfile="$HOME/.clustermgr/celery.pid" --logfile="$HOME/.clustermgr/celery.log" --detach
    echo "Starting Celery Beat"
    celery beat -A clusterapp.celery --pidfile="$HOME/.clustermgr/celery-beat.pid" --logfile="$HOME/.clustermgr/celery-beat.log" -s "$HOME/.clustermgr/celerybeat-schedule" --detach
    echo "Starting Gunicorn Web Server"
    gunicorn --daemon -w 2 -b 127.0.0.1:5000 clusterapp:app
}

stop() {
    
    echo "Stopping Celery Workers"
    ps auxww | grep 'celery worker' | awk '{print $2}' | xargs kill -9
    rm "$HOME/.clustermgr/celery.pid"
    echo "Stopping Celery Beats"
    ps auxww | grep 'celery beat' | awk '{print $2}' | xargs kill -9
    rm "$HOME/.clustermgr/celery-beat.pid"
    echo "Stopping Gunicorn Web Server"
    ps auxww | grep 'gunicorn --daemon' | awk '{print $2}' | xargs kill -9

}

restart() {
    stop
    start
}



case "$1" in
    start)
        start
    ;;

    stop)
        stop
    ;;


    restart)
        restart
    ;;

    *)
        echo "Usage: clustermgr-cli {start|stop|restart}"
        exit 64
    ;;
esac
