"""add GServer model

Revision ID: 323ee67934b1
Revises: 555f03405e07
Create Date: 2020-01-14 12:22:14.369388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323ee67934b1'
down_revision = '555f03405e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=250), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('server_type', sa.String(length=10), nullable=True),
    sa.Column('jsondata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generic_server')
    # ### end Alembic commands ###
