"""empty message

Revision ID: 391d9f3595a3
Revises: 255ca6770841
Create Date: 2017-09-26 21:52:28.068674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391d9f3595a3'
down_revision = '255ca6770841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appconfig', sa.Column('gluu_version', sa.String(length=10), nullable=True))
    op.add_column('appconfig', sa.Column('primary_server', sa.Integer(), nullable=True))
    op.add_column('appconfig', sa.Column('use_ip_for_replication', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'appconfig', 'ldapServer', ['primary_server'], ['id'])
    op.drop_column('ldapServer', 'gluu_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ldapServer', sa.Column('gluu_version', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'appconfig', type_='foreignkey')
    op.drop_column('appconfig', 'use_ip_for_replication')
    op.drop_column('appconfig', 'primary_server')
    op.drop_column('appconfig', 'gluu_version')
    # ### end Alembic commands ###
