"""adds primary server and others to appconfig

Revision ID: 391d9f3595a3
Revises: 255ca6770841
Create Date: 2017-09-26 21:52:28.068674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391d9f3595a3'
down_revision = '255ca6770841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appconfig") as batch_op:
        batch_op.add_column(sa.Column('gluu_version', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('primary_server', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('use_ip_for_replication', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key("pk_ldapServer", 'ldapServer', ['primary_server'], ['id'])

    with op.batch_alter_table("ldapServer") as batch_op:
        batch_op.drop_column('gluu_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ldapServer") as batch_op:
        batch_op.add_column(sa.Column('gluu_version', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table("appconfig") as batch_op:
        batch_op.drop_column('use_ip_for_replication')
        batch_op.drop_column('primary_server')
        batch_op.drop_column('gluu_version')
        batch_op.drop_constraint("pk_ldapServer", type_='foreignkey')
    # ### end Alembic commands ###
