"""empty message

Revision ID: 394bc54519a2
Revises: 85d04a42bba6
Create Date: 2017-09-20 22:01:05.215879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394bc54519a2'
down_revision = '85d04a42bba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ldapServer', sa.Column('replicator_password', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ldapServer', 'replicator_password')
    # ### end Alembic commands ###
