"""empty message

Revision ID: 85d04a42bba6
Revises: 
Create Date: 2017-09-20 18:54:59.569079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d04a42bba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replication_dn', sa.String(length=200), nullable=True),
    sa.Column('replication_pw', sa.String(length=200), nullable=True),
    sa.Column('certificate_folder', sa.String(length=200), nullable=True),
    sa.Column('last_test', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyrotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('oxeleven_url', sa.String(length=255), nullable=True),
    sa.Column('oxeleven_token', sa.LargeBinary(), nullable=True),
    sa.Column('oxeleven_token_key', sa.LargeBinary(), nullable=True),
    sa.Column('oxeleven_token_iv', sa.LargeBinary(), nullable=True),
    sa.Column('inum_appliance', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ldapServer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fqn_hostname', sa.String(length=150), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('initialized', sa.Boolean(), nullable=True),
    sa.Column('setup', sa.Boolean(), nullable=True),
    sa.Column('ldap_password', sa.String(length=150), nullable=True),
    sa.Column('gluu_server', sa.Boolean(), nullable=True),
    sa.Column('gluu_version', sa.String(length=10), nullable=True),
    sa.Column('ldap_user', sa.String(length=20), nullable=True),
    sa.Column('ldap_group', sa.String(length=20), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fqn_hostname')
    )
    op.create_table('ldap_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=150), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('tls_cacert', sa.Text(), nullable=True),
    sa.Column('tls_servercert', sa.Text(), nullable=True),
    sa.Column('tls_serverkey', sa.Text(), nullable=True),
    sa.Column('initialized', sa.Boolean(), nullable=True),
    sa.Column('setup', sa.Boolean(), nullable=True),
    sa.Column('admin_pw', sa.String(length=150), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('gluu_server', sa.Boolean(), nullable=True),
    sa.Column('gluu_version', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ldap_server.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('logging_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oxauth_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('gluu_server', sa.Boolean(), nullable=True),
    sa.Column('gluu_version', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oxeleven_key_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiMaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmr_id', sa.Integer(), nullable=True),
    sa.Column('replicator', sa.Boolean(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mmr_id'], ['ldap_server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiMaster')
    op.drop_table('oxeleven_key_id')
    op.drop_table('oxauth_server')
    op.drop_table('logging_server')
    op.drop_table('ldap_server')
    op.drop_table('ldapServer')
    op.drop_table('keyrotation')
    op.drop_table('appconfig')
    # ### end Alembic commands ###
