"""empty message

Revision ID: 8787a1173752
Revises: 
Create Date: 2020-04-13 18:30:59.991748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8787a1173752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_param',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_param')
    # ### end Alembic commands ###
