"""adds primary server and others to appconfig

Revision ID: f9f5d69bb732
Revises: 255ca6770841
Create Date: 2017-09-27 15:22:03.046956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f5d69bb732'
down_revision = '255ca6770841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appconfig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gluu_version', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('primary_server', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('use_ip_for_replication', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_ldapServer_id', 'ldapServer', ['primary_server'], ['id'])

    with op.batch_alter_table('ldapServer', schema=None) as batch_op:
        batch_op.drop_column('gluu_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ldapServer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gluu_version', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('appconfig', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ldapServer_id', type_='foreignkey')
        batch_op.drop_column('use_ip_for_replication')
        batch_op.drop_column('primary_server')
        batch_op.drop_column('gluu_version')

    # ### end Alembic commands ###
