"""empty message

Revision ID: fe94fb3492c2
Revises: 394bc54519a2
Create Date: 2017-09-21 23:50:53.928968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe94fb3492c2'
down_revision = '394bc54519a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ldap_server')
    op.drop_column('ldapServer', 'replicator_password')
    op.drop_constraint(None, 'multiMaster', type_='foreignkey')
    op.create_foreign_key(None, 'multiMaster', 'ldapServer', ['mmr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multiMaster', type_='foreignkey')
    op.create_foreign_key(None, 'multiMaster', 'ldap_server', ['mmr_id'], ['id'])
    op.add_column('ldapServer', sa.Column('replicator_password', sa.VARCHAR(length=150), nullable=True))
    op.create_table('ldap_server',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hostname', sa.VARCHAR(length=150), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('port', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), nullable=True),
    sa.Column('protocol', sa.VARCHAR(length=10), nullable=True),
    sa.Column('tls_cacert', sa.TEXT(), nullable=True),
    sa.Column('tls_servercert', sa.TEXT(), nullable=True),
    sa.Column('tls_serverkey', sa.TEXT(), nullable=True),
    sa.Column('initialized', sa.BOOLEAN(), nullable=True),
    sa.Column('setup', sa.BOOLEAN(), nullable=True),
    sa.Column('admin_pw', sa.VARCHAR(length=150), nullable=True),
    sa.Column('provider_id', sa.INTEGER(), nullable=True),
    sa.Column('gluu_server', sa.BOOLEAN(), nullable=True),
    sa.Column('gluu_version', sa.VARCHAR(length=10), nullable=True),
    sa.CheckConstraint(u'gluu_server IN (0, 1)'),
    sa.CheckConstraint(u'initialized IN (0, 1)'),
    sa.CheckConstraint(u'setup IN (0, 1)'),
    sa.ForeignKeyConstraint(['provider_id'], [u'ldap_server.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    # ### end Alembic commands ###
